easyexception/__init__.py,sha256=h0AdTz75cpL61MCb_T1oHAAYFY-hBQZaF735eoXjz4w,23
easyexception/exception.py,sha256=5LrcjJtSH75pTlsaVahQMRodna1vI3L7EWir-npHzSk,1208
easyexception-0.0.2.dist-info/LICENSE,sha256=ACwmltkrXIz5VsEQcrqljq-fat6ZXAMepjXGoe40KtE,1069
easyexception-0.0.2.dist-info/METADATA,sha256=ZZuPrXjV82K1OcBlW-LwAbvu75q-NOa628X69FFbRc4,2411
easyexception-0.0.2.dist-info/WHEEL,sha256=U88EhGIw8Sj2_phqajeu_EAi3RAo8-C6zV3REsWbWbs,92
easyexception-0.0.2.dist-info/top_level.txt,sha256=_5TMdX5ZJeAudHe1o6fAEJK1TpwA4bVLxng4CU1mfWI,14
easyexception-0.0.2.dist-info/RECORD,,
